- name: iDRAC Test
  hosts: all
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: Get system inventory
      dellemc.openmanage.idrac_system_info:
        idrac_ip: "{{ oob_host }}"
        idrac_user: "{{ user }}"
        idrac_password:  "{{ password }}"
        validate_certs: False