- name: Get system inventory
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: Simple A record (IPV4 address) lookup
      ansible.builtin.debug:
        msg: "{{ lookup('community.general.dig', oob_host)}}"

    - name: Get system inventory.
      dellemc.openmanage.idrac_system_info:
        idrac_ip: "{{ oob_host }}"
        idrac_user: "{{ user }}"
        idrac_password:  "{{ password }}"
        validate_certs: False